# Generated by Django 5.2.2 on 2025-08-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='credly',
            field=models.URLField(blank=True, null=True),
        ),
    ]
