# Generated by Django 5.2.2 on 2025-06-09 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_experience_profile_email_profile_github_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='icon_class',
            field=models.CharField(default='fas fa-code', help_text='e.g., fab fa-python', max_length=50),
        ),
    ]
