# Generated by Django 5.2.2 on 2025-06-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_skill_icon_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='badge_image',
            field=models.ImageField(blank=True, null=True, upload_to='certifications/'),
        ),
    ]
