# Generated by Django 5.2.2 on 2025-08-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_profile_credly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('Python', 'Data'), ('SQL', 'Data'), ('Pandas', 'Data'), ('NumPy', 'Data'), ('ML Integration', 'Data'), ('Data Wrangling', 'Data'), ('Automation Scripts', 'Backend'), ('Django', 'Backend'), ('Git', 'DevOps'), ('UX for Data', 'Frontend'), ('Dashboard Design', 'Frontend'), ('Problem Solving', 'Other'), ('Communication', 'Other')], default='Other', max_length=20),
        ),
    ]
