# Generated by Django 5.2.2 on 2025-08-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_skill_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='badge_image',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='badge_url',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='title',
        ),
        migrations.AddField(
            model_name='certification',
            name='credential_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='credential_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='certification',
            name='issuer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
