# Generated by Django 5.2.2 on 2025-08-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_certification_badge_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='issue_date',
        ),
        migrations.AddField(
            model_name='certification',
            name='expiration_date_month',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='expiration_date_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='issue_date_month',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='issue_date_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='certification',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
