# Generated by Django 5.2.2 on 2025-06-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_skill_category_alter_skill_icon_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='skills_used',
            field=models.ManyToManyField(blank=True, to='main.skill'),
        ),
    ]
