# Generated by Django 5.2.2 on 2025-08-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_certification_issue_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certification',
            options={'ordering': ['-issue_date_year', '-issue_date_month']},
        ),
        migrations.AddField(
            model_name='certification',
            name='issuer_logo',
            field=models.ImageField(blank=True, null=True, upload_to='cert_logos/'),
        ),
    ]
