# Generated by Django 5.2.2 on 2025-09-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_description_education_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyVisitorStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('unique_visitors', models.PositiveIntegerField(default=0)),
                ('total_page_views', models.PositiveIntegerField(default=0)),
                ('new_visitors', models.PositiveIntegerField(default=0)),
                ('returning_visitors', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Daily Visitor Stats',
                'verbose_name_plural': 'Daily Visitor Stats',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PopularPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_path', models.CharField(max_length=500, unique=True)),
                ('page_title', models.CharField(blank=True, max_length=200)),
                ('visit_count', models.PositiveIntegerField(default=0)),
                ('last_visited', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Popular Page',
                'verbose_name_plural': 'Popular Pages',
                'ordering': ['-visit_count'],
            },
        ),
        migrations.CreateModel(
            name='VisitorCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Total Visitor Count',
                'verbose_name_plural': 'Total Visitor Count',
            },
        ),
        migrations.CreateModel(
            name='VisitorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('referrer', models.URLField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('first_visit', models.DateTimeField(auto_now_add=True)),
                ('last_visit', models.DateTimeField(auto_now=True)),
                ('page_views', models.PositiveIntegerField(default=1)),
                ('is_returning', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Visitor Session',
                'verbose_name_plural': 'Visitor Sessions',
                'ordering': ['-first_visit'],
            },
        ),
        migrations.CreateModel(
            name='VisitorGeolocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('visitor_count', models.PositiveIntegerField(default=0)),
                ('last_visit', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Visitor Location',
                'verbose_name_plural': 'Visitor Locations',
                'ordering': ['-visitor_count'],
                'unique_together': {('country', 'city')},
            },
        ),
    ]
